spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
  devtools:
    livereload:
      enabled: true

application:
  security:
    jwt:
      secret-key: E4F56E4FDC9BDCA24F48C9B56EED0DED4942372A744D8651290B5713AEA876DF
      expiration: 86400000
      refresh-token:
        expiration: 604800000
logging:
  level:
    web: debug